# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: "0 6 * * *"
  release:
    types: [published]
  watch:
    types: [started]

permissions:
  contents: read

jobs:
  Call-APi:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@v1.1.1
        with:
          timezone: Asia/Shanghai
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: run
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          # run with args
          python main.py --t "$TOKEN" >> ./run.log
          tail run.log
      - name: Commit log
        env:
          NAME: yc7521
          EMAIL: 752106133@qq.com
        run: |
          git config --global user.name "$NAME"
          git config --global user.email "$EMAIL"
          git add .
          git commit -m "update log" -a
      - name: Push log
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
